{
  imports = [
    ./bat.nix
    ./btop.nix
    ./bun.nix
    ./cava.nix
    ./cavalier.nix
    ./chromium.nix
    ./eza.nix
    ./fastfetch.nix
    ./fzf.nix
    ./gemini-commit.nix
    ./ghostty.nix
    ./git.nix
    ./go-encryption.nix
    ./go.nix
    ./kitty.nix
    ./lazygit.nix
    ./nh.nix
    ./nvf.nix
    ./obs-studio.nix
    ./oh-my-posh.nix
    ./spicetify.nix
    ./vscode.nix
    ./yazi.nix
    ./zed-editor.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
